### ISSUE TITLE
[TD] Linux Covert Ops undefined Tile 

### ISSUE THREAD

**Issue by Gerwin2k** [TheAssemblyArmada/Vanilla-Conquer#734]
Followup on:
[TD] Addon mixfile loading fails on non-Windows OSes #730 

I can only reproduce this on Linux, not on Windows.

In the Covert Ops mission "infiltrated" there is an undefined tile. When the map is explored it will not display correctly. When the radar is active it will also crash the game quickly after it becomes visible. See attached image.

![linux-infitrated-undefined-tile](https://user-images.githubusercontent.com/39087372/148692427-07c67a23-eb5b-439e-b508-171255ce547f.png)

The insert on the bottom right of the image is what the tile looks like in Windows.

**Comment by giulianobelinassi** [comment]
Which mix file is this asset located? It may be another wrong path separator problem.

**Comment by giulianobelinassi** [comment]
It may be worth guarding the radar code if the game fails to load some tiles.

**Comment by Gerwin2k** [comment]
The tile is a match with "p04.des" inside "desert.mix".
Strange, because obviously most of the desert.mix content is drawn properly.

**Comment by Gerwin2k** [comment]
I found the cause, somewhat.
In my game folder was an archive with the converted Nintendo 64 missions, called sc-n64.mix.
Dated 2012-05-17 20:42, 206536 bytes, originated from a downloaded package "miniTD-CNC95-v11". 

It has 15 files inside, and the last one is a custom "p04.des" terrain graphic. It has two frames instead of one. The first frame is the same pair of rocks as the original, and the second frame shows some debris, debris of a broken machine.

This custom tile is trouble in the Linux version of VanillaTD, but the windows versions seems to run OK with it. 

Should I close this ticket? I figure in the future someone else may encounter this nasty issue and you can waste a lot of time searching for a clue.

**Comment by OmniBlade** [comment]
Maybe attach the mix file to this issue for future investigation and leave the issue open so it can be investigated?

**Comment by giulianobelinassi** [comment]
I'd say vanilla should support console missions as well, so this issue should be fixed.

**Comment by Gerwin2k** [comment]
[sc-n64.zip](https://github.com/TheAssemblyArmada/Vanilla-Conquer/files/7848341/sc-n64.zip)
Sounds like a plan. The culprit mix file "sc-n64.mix" is attached to this post.

**Comment by Nyerguds** [comment]
The N64 version has a specific Desert version of that infamous "UFO" tile P04.

To get that into the missions without modding the normal P04 tile, I edited the original P04.DES tile and added an extra tile to it. Since the game references tiles by specific cell, this extra tile has no effect on anything. Then I hex edited the N64 desert maps to use P04 cell index 1 instead of 0.

This issue seems to point to Vanilla Conquer not correctly reading template files from sc*.mix files.

The original game never had radar crashes on missing graphics for empty tiles, either.

**Comment by OmniBlade** [comment]
I've tried this recently with the provided mix file and I still get the missing tile and the crash on linux. The mix file is being read though as the N64 missions show up in the new missions menu.
